registry:
  container_name: registry
  restart: always
  image: registry:2
  ports:
    - 80:5000
  environment:
    REGISTRY_STORAGE: "s3"
    REGISTRY_STORAGE_S3_ACCESSKEY: "{{ aws_key }}"
    REGISTRY_STORAGE_S3_SECRETKEY: "{{ aws_secret_key }}"
    REGISTRY_STORAGE_S3_REGION: "{{ aws_region }}"
    REGISTRY_STORAGE_S3_BUCKET: "{{ bucket_name }}"
    REGISTRY_STORAGE_S3_ENCRYPT: "true"
    REGISTRY_STORAGE_S3_SECURE: "true"
    REGISTRY_STORAGE_S3_V4AUTH: "true"
    REGISTRY_AUTH: "htpasswd"
    REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
    REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
  volumes:
    - {{ auth_path }}:/auth
